-- 1. ユーザーテーブル (users)
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. 現在育成中キャラクターテーブル (current_character)
CREATE TABLE IF NOT EXISTS current_character (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    stage VARCHAR(20) NOT NULL,
    generation INT NOT NULL,
    action_count INT NOT NULL,
    hp INT NOT NULL,
    atk INT NOT NULL,
    def INT NOT NULL,
    str INT NOT NULL,
    int_stat INT NOT NULL,
    chm INT NOT NULL,
    spd INT NOT NULL,
    action_logs TEXT,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- 3. 完成図鑑コレクションテーブル (character_dex)
CREATE TABLE IF NOT EXISTS character_dex (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    generation INT NOT NULL,
    character_number INT NOT NULL,
    character_name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    hp INT NOT NULL,
    atk INT NOT NULL,
    def INT NOT NULL,
    str INT NOT NULL,
    int_stat INT NOT NULL,
    chm INT NOT NULL,
    spd INT NOT NULL,
    history_summary TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);
